import { test, expect } from '@playwright/test';

// Playwright will now automatically attach the Clerk login session (user.json) generated by auth.setup.ts.

test.describe('Authenticated API Tests', () => {

  test('POST /api/create-order should reject invalid coupons with valid auth', async ({ request }) => {
    const adminApiKey = (process.env.ADMIN_API_KEY || 'shivam_secure_api_key_2026').trim();
    
    // 1. Send the request EXACTLY how the browser sends it (Cookies are attached automatically!)
    const response = await request.post('/api/create-order', {
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': adminApiKey,
      },
      data: {
        courseId: "python-beginners-live-01",
        currency: "INR",
        couponCode: "FAKE_COUPON_123", // 🚨 This should trigger the 400 Error
        userId: "test_user_123" // The backend verifies the real ID using the Clerk cookie anyway
      }
    });

    // 2. Optional: Log the response if it fails so we can debug
    const responseText = await response.text();
    if (response.status() !== 400) {
      console.log("🚨 UNEXPECTED API RESPONSE:", responseText);
    }
    
    // 3. Validate Status Code (Should be 400 Bad Request, NOT 401 Unauthorized)
    expect(response.status()).toBe(400);
    
    // 4. Validate the JSON error message matches our business logic
    const responseBody = JSON.parse(responseText);
    expect(responseBody.success).toBe(false);
    expect(responseBody.error).toBe('Invalid coupon code');
  });

});